---
title: "Quiz 160518"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width = 180)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz0518 <- read.xlsx("../data/quiz0518.xlsx", 1, startRow = 2, endRow = 66, colIndex = c(3:7, 9:14), colClasses = c(rep("character", 11)), stringsAsFactors = FALSE)
str(quiz0518)
names(quiz0518) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group")
quiz0518$dept <- factor(quiz0518$dept)
quiz0518$year <- factor(quiz0518$year)
quiz0518$group <- factor(quiz0518$group, levels = c("Red", "Black"))
quiz0518$Q1 <- factor(quiz0518$Q1, levels = c("가", "나", "다", "라"), labels = c("열에 한명", "열에 세명", "열에 다섯명", "열에 여덟명"))
quiz0518$Q2 <- factor(quiz0518$Q2, levels = c("가", "나", "다", "라"), labels = c("15%", "25%", "45%", "65%"))
quiz0518$Q3 <- factor(quiz0518$Q3, levels = c("가", "나", "다", "라"), labels = c("1명", "2명", "3명", "4명"))
# quiz0518$Q4.2 <- quiz0518$Q4
Black <- quiz0518$group == "Black"
Red <- quiz0518$group == "Red"
# quiz0518$Q4.2[quiz0518$group == "Black" & quiz0518$Q4 == "가"] <- "400명은 죽는다"
# quiz0518$Q4.2[quiz0518$group == "Black" & quiz0518$Q4 == "나"] <- "모두 사망 않을 확률 1/3"
# quiz0518$Q4.2[quiz0518$group == "Red" & quiz0518$Q4 == "가"] <- "200명은 살린다"
# quiz0518$Q4.2[quiz0518$group == "Red" & quiz0518$Q4 == "나"] <- "모두 살릴 확률 1/3"
# quiz0518$Q4.2 <- quiz0518$Q4
quiz0518$Q4.2[Red] <- ifelse(quiz0518$Q4[Red] == "가", "200명/400명", ifelse(quiz0518$Q4[Red] == "나", "확률 1/3", NA))
quiz0518$Q4.2[Black] <- ifelse(quiz0518$Q4[Black] == "가", "200명/400명", ifelse(quiz0518$Q4[Black] == "나", "확률 1/3", NA))
str(quiz0518)
```

```{r, randomization, echo = FALSE, results = 'hide'}
pander(summary(quiz0518))
```

### 퀴즈 응답 비교

#### Latane and Darley

##### 방관자 효과

```{r, bystander, echo = FALSE}
pander(addmargins(table(quiz0518$group, quiz0518$Q1, exclude = NULL), margin = 1)[-3, ])
```

##### 방관자 효과(%)

```{r, bystander in percentage, echo = FALSE}
pander(round(prop.table(addmargins(table(quiz0518$group, quiz0518$Q1, exclude = NULL), margin=1), margin=1)[4,]*100, digits=1), caption = "방관자 효과")
```

#### Stanley Milgram

##### 450V까지 누르는 사람

```{r, obedience, echo = FALSE}
pander(addmargins(table(quiz0518$group, quiz0518$Q2, exclude = NULL), margin = 1)[-3, ])
```

##### 450V까지 누르는 사람 (%)

```{r, obedience in percentage, echo = FALSE}
pander(round(prop.table(addmargins(table(quiz0518$group, quiz0518$Q2, exclude = NULL), margin = 1), margin = 1)[4, ]*100, digits = 1), caption = "스탬리 밀그램 : 복종")
```

#### Solomon Asch

##### Power of 3

```{r, Power of 3, echo = FALSE}
pander(addmargins(table(quiz0518$group, quiz0518$Q3, exclude = NULL), margin = 1)[-3, ])
```

##### Power of 3 (%)

```{r, Power of 3 in percentage, echo = FALSE}
pander(round(prop.table(addmargins(table(quiz0518$group, quiz0518$Q3, exclude = NULL), margin = 1), margin = 1)[4, ]*100, digits = 1), caption = "Power of 3")
```

### Framing Effect

#### 삶과 죽음

##### 600명 중 200명이 사는 거나 400명이 죽는 것, 모두 살리는 거나 모두 죽지 않는 것이나 같은 내용임에도 반응이 다르게 나타남에 유의. 손실회피 경향과 같은 현상을 관찰할 수 있음.

```{r, Framing Effect, echo = FALSE}
tbl <- table(quiz0518$group, quiz0518$Q4.2, exclude = NULL)
rownames(tbl) <- c("Red(산다, 모두 살릴)", "Black(죽는다, 모두 죽지 않을)", "NA")
kable(tbl[1:2, ], caption = "Framing Effect")
```

##### % 비교.  

```{r, Framing effects in percentage, echo = FALSE}
tbl.p.a <- addmargins(round(prop.table(tbl[1:2, -3], margin = 1)*100, digits = 1))[1:2, ]
colnames(tbl.p.a)[3] <- "계"
kable(tbl.p.a)
```

```{r, save, echo = FALSE}
#save.image("../R/quiz0518.rda")
```