---
title: "Red_and_Black_160314"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
```

#### Data 

```{r, data}
class_roll <- read.xlsx("../data/literacy_RnB0308.xlsx", 1, startRow = 2, endRow = 66, colIndex = c(3:7, 9, 17:19), colClasses=rep("character", 9), stringsAsFactors = FALSE)
str(class_roll)
class_roll$Q8 <- factor(class_roll$Q8, levels = c("가", "나"), labels = c("Male", "Female"))
class_roll$Q9 <- factor(class_roll$Q9, levels = c("가", "나"), labels = c("Yes", "No"))
class_roll$Q10 <- factor(class_roll$Q10, levels = c("가", "나", "다", "라"), labels = c("Seoul", "Gyunggi", "Gangwon", "Others"))
names(class_roll) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "gender", "eye_glasses", "hs_location")
str(class_roll)
```

#### Randomization

```{r, randomization}
set.seed(71)
N <- nrow(class_roll) 
red.id <- sample(1:N, size=floor(N/2))
red.id
class_roll$group <- factor(ifelse((1:N) %in% red.id, "red", "black"), levels = c("red", "black"))
black.id<-(1:N)[-red.id]
```
----

### Randomization Effects

```{r, colleges}
#pander(class_roll)
#table("단과대학" = class_roll$college, "그룹" = class_roll$group)
```

#### ID years 15

```{r, id 15}
ID.15<-factor(ifelse(substr(class_roll$id, 1, 4) >= 2015, "younger.15", "older.15"), levels=c("younger.15", "older.15"))
pander(table("그룹" = class_roll$group, "15학번 기준" = ID.15))
```

#### ID years 14

```{r, id 14}
ID.14<-factor(ifelse(substr(class_roll$id, 1, 4) >= 2014, "younger.14", "older.14"), levels=c("younger.14", "older.14"))
pander(table("그룹" = class_roll$group, "14학번 기준" = ID.14))
```

#### ID years 13

```{r, id 13}
ID.13<-factor(ifelse(substr(class_roll$id, 1, 4) >= 2013, "younger.13", "older.13"), levels=c("younger.13", "older.13"))
pander(table("그룹" = class_roll$group, "13학번 기준" = ID.13))
```

#### ID years 12

```{r, id 12}
ID.12<-factor(ifelse(substr(class_roll$id, 1, 4) >= 2012, "younger.12", "older.12"), levels=c("younger.12", "older.12"))
pander(table("그룹" = class_roll$group, "12학번 기준" = ID.12))
```

#### ID last digit, odd or even

```{r, odd or even}
odd.even <- as.numeric(class_roll$id) %% 2
odd.even.f <- factor(odd.even, levels=c(1, 0), labels = c("홀수", "짝수"))
pander(table("Group"= class_roll$group, "홀짝" = odd.even.f))
# kable(table("홀짝" = odd.even.f, "Group"= class_roll$group))
```

#### Last name 

```{r, name}
f.name <- substring(class_roll$name, first = 1, last = 1)
# f.name %in% c("김","이","박")
f.name.f <- factor(ifelse(f.name %in% c("김", "이", "박"), f.name, "기타"), levels=c("김", "이", "박", "기타"))
pander(table("Group" = class_roll$group, "Family Name" = f.name.f))
```

#### School Year

```{r, year}
year.f <- factor(class_roll$year, labels = c("1학년", "2학년", "3학년", "4학년"))
pander(table("Group" = class_roll$group, "학년" = year.f))
```

#### e-mail service

```{r, e_mail}
e.mail.list <- strsplit(class_roll$e.mail, "@", fixed = TRUE)
mail.com <- mapply("[", e.mail.list, 2)
mail.com.f <- factor(ifelse(mail.com == "naver.com", "네이버", "기타서비스"), levels = c("네이버", "기타서비스"))
pander(table("그룹" = class_roll$group, "e-mail" = mail.com.f))
```

#### Gender

```{r, gender}
pander(table("그룹" = class_roll$group, "Gender" = class_roll$gender))
```

#### Eyglasses

```{r, eyeglasses}
pander(table("그룹" = class_roll$group, "Eye_Glasses" = class_roll$eye_glasses))
```

#### High School Location

```{r, High school location}
pander(table("그룹" = class_roll$group, "HS_Location" = class_roll$hs_location))
```
----

### Roll Divided

```{r, list, echo=FALSE, message=FALSE, results='hide'}
gr.id.o <- order(class_roll$group, class_roll$id)
id.by.gr <- class_roll[gr.id.o, c("group", "id", "name")]
red.names <- id.by.gr[id.by.gr$group=="red", c("id", "name")]
pander(red.names)
black.names <- id.by.gr[id.by.gr$group=="black", c("id", "name")]
pander(black.names)
# class_roll[red.id, "id"]
# class_roll[black.id, "id"]
# cbind(class_roll[red.id, "id"], class_roll[black.id, "id"])
#red.black.list <- list("Red" = red.names, "Black" = black.names, row.names = NULL)
red.black.df <- data.frame("Red" = red.names, "Black" = black.names, row.names = NULL)
# names(red.black.df) <- c("Red", "Black")
# pander(red.black.list)
# kable(red.black.df, align = c("c", "c", "c", "c"))
```

```{r, print_out, echo=FALSE}
pander(red.black.df)
```

```{r, save, echo=FALSE, message=FALSE, results='hide'}
save.image("../R/red_and_black_160314_data.rda")
```